# https://alacritty.org/config-alacritty.html

import = [
    "~/.config/alacritty/colorscheme.toml"
]

[font]
size = 16
offset = { x = 0, y = 8 }

[font.normal]
family = "UbuntuMono Nerd Font"
# family = "Menlo"

[font.bold]

[window]
decorations = "none"
# startup_mode = "fullscreen"
title = "Terminal"
dynamic_title = false

[window.padding]
x = 10
y = 10
