[colors.primary]
background  = "#2a2c3c"
foreground  = "#c6d0f5"

[colors.normal]
black       = "#414559"
red         = "#e78284"
green       = "#a6d189"
yellow      = "#e5c890"
blue        = "#8caaee"
magenta     = "#ca9ee6"
cyan        = "#81c8be"
white       = "#c6d0f5"

[colors.bright]
black       = "#51576d"
red         = "#ea999c"
green       = "#b3d39c"
yellow      = "#ef9f76"
blue        = "#99d1db"
magenta     = "#babbf1"
cyan        = "#99d1db"
white       = "#b5bfe2"

[colors.cursor]
text        = "CellBackground"
cursor      = "CellForeground"

[colors.selection]
text        = "CellForeground"
background  = "#5c6370"
