# Default colors
[colors.primary]
background = '#1c1c1c'
foreground = '#b7b7b7'

# Normal colors
[colors.normal]
black   = '#1c1c1c'
red     = '#d1845d'
green   = '#87af87'
yellow  = '#afaf87'
blue    = '#87afd7'
magenta = '#a580a5'
cyan    = '#87afaf'
white   = '#b7b7b7'

# Bright colors
[colors.bright]
black   = '#1c1c1c'
red     = '#d1845d'
green   = '#87af87'
yellow  = '#afaf87'
blue    = '#87afd7'
magenta = '#a580a5'
cyan    = '#87afaf'
white   = '#b7b7b7'

# [[colors.indexed_colors]]
# index = 16
# color = '#d18616'

# [[colors.indexed_colors]]
# index = 17
# color = '#ff938a'
# # Codedark colors for Alacritty

# # Default colors
# [colors.primary]
# background = '#1E1E1E'
# foreground = '#D4D4D4'

# # Normal colors
# [colors.normal]
# black   = '#1E1E1E'
# red     = '#D16969'
# green   = '#608B4E'
# yellow  = '#DCDCAA'
# blue    = '#569CD6'
# magenta = '#C586C0'
# cyan    = '#4EC9B0'
# white   = '#D4D4D4'

# # Bright colors
# [colors.bright]
# black   = '#1E1E1E'
# red     = '#D16969'
# green   = '#608B4E'
# yellow  = '#DCDCAA'
# blue    = '#569CD6'
# magenta = '#C586C0'
# cyan    = '#4EC9B0'
# white   = '#D4D4D4'
