[colors.primary]
background = "#242424"
foreground = "#cdd6f4"
bright_foreground = "#FFFFFF"

[colors.cursor]
text = "#292A35"
cursor = "#F6F6F5"

[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.selection]
text = "CellForeground"
background = "#7C7F8A"

[colors.normal]
black = "#282828"
#red = "#DD6E6B"
red = "#fab386"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#cba6f7"
cyan = "#A7DFEF"
white = "#F6F6F5"

[colors.bright]
black = "#1C1C1C"
# red = "#DD6E6B"
red = "#fab386"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#cba6f7"
cyan = "#A7DFEF"
white = "#F6F6F5"

[colors.search.matches]
foreground = "#7C7F8A"
background = "#87E58E"

[colors.search.focused_match]
foreground = "#7C7F8A"
background = "#FDC38E"

[colors.footer_bar]
background = "#292A35"
foreground = "#F6F6F5"

[colors.hints.start]
foreground = "#292A35"
background = "#E8EDA2"

[colors.hints.end]
foreground = "#E8EDA2"
background = "#292A35"
