#onedark
[colors.primary]
background  = "#282c34"
foreground  = "#abb2bf"

[colors.normal]
black       = "#282c34"
red         = "#e06c75"
green       = "#98c379"
yellow      = "#e5c07b"
blue        = "#61afef"
magenta     = "#c678dd"
cyan        = "#56b6c2"
white       = "#abb2bf"

[colors.bright]
black       = "#3e4451"
red         = "#e9969d"
green       = "#b3d39c"
yellow      = "#edd4a6"
blue        = "#8fc6f4"
magenta     = "#d7a1e7"
cyan        = "#7bc6d0"
white       = "#c8cdd5"

[colors.cursor]
text        = "CellBackground"
cursor      = "CellForeground" # syntax-cursor-color

[colors.selection]
text        = "CellForeground"
background  = "#5c6370"


# Default colors
# [colors.primary]
# background = '#1c1c1c'
# foreground = '#b7b7b7'

# # Normal colors
# [colors.normal]
# black   = '#1c1c1c'
# red     = '#d1845d'
# green   = '#87af87'
# yellow  = '#afaf87'
# blue    = '#87afd7'
# magenta = '#a580a5'
# cyan    = '#87afaf'
# white   = '#b7b7b7'

# # Bright colors
# [colors.bright]
# black   = '#1c1c1c'
# red     = '#d1845d'
# green   = '#87af87'
# yellow  = '#afaf87'
# blue    = '#87afd7'
# magenta = '#a580a5'
# cyan    = '#87afaf'
# white   = '#b7b7b7'

# [[colors.indexed_colors]]
# index = 16
# color = '#d18616'

# [[colors.indexed_colors]]
# index = 17
# color = '#ff938a'
# # Codedark colors for Alacritty

# # Default colors
# [colors.primary]
# background = '#1E1E1E'
# foreground = '#D4D4D4'

# # Normal colors
# [colors.normal]
# black   = '#1E1E1E'
# red     = '#D16969'
# green   = '#608B4E'
# yellow  = '#DCDCAA'
# blue    = '#569CD6'
# magenta = '#C586C0'
# cyan    = '#4EC9B0'
# white   = '#D4D4D4'

# # Bright colors
# [colors.bright]
# black   = '#1E1E1E'
# red     = '#D16969'
# green   = '#608B4E'
# yellow  = '#DCDCAA'
# blue    = '#569CD6'
# magenta = '#C586C0'
# cyan    = '#4EC9B0'
# white   = '#D4D4D4'
