#!/bin/bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

# alacritty terminal
rm -rf $HOME/.alacritty.toml
rm -rf $HOME/.config/alacritty
mkdir $HOME/.config/alacritty
ln -s $DOTFILES/alacritty/alacritty.toml $HOME/.alacritty.toml
ln -s $DOTFILES/alacritty/habamax.toml $HOME/.config/alacritty/habamax.toml

# kitty terminal
rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

# aliases
rm -rf $HOME/.aliases
ln -s $DOTFILES/zsh/aliases $HOME/.aliases

# zsh
rm -rf $HOME/.zsh
rm -rf $HOME/.zshrc
rm -rf $HOME/.zprofile
rm -rf $HOME/.zshenv
ln -s $DOTFILES/zsh/core/ $HOME/.zsh
ln -s $DOTFILES/zsh/zshenv $HOME/.zshenv
ln -s $DOTFILES/zsh/zshrc $HOME/.zshrc
ln -s $DOTFILES/zsh/zprofile $HOME/.zprofile


# tmux
rm -rf $HOME/.tmux.conf
ln -s $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

# scripts
mkdir -p $HOME/.local/bin
rm -rf $HOME/.local/bin/t
ln -s $DOTFILES/scripts/t $HOME/.local/bin/t

# git
rm -rf $HOME/.gitconfig
ln -s $DOTFILES/git/gitconfig $HOME/.gitconfig

# nvim
rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

# php refactoring tools
rm -rf $HOME/.config/phpactor
ln -s $DOTFILES/phpactor $HOME/.config/phpactor

# rubocop
rm -rf $HOME/.rubocop.yml
ln -s $DOTFILES/rubocop/rubocop.yml $HOME/.rubocop.yml

# solargraph
rm -rf $HOME/.solargraph.yml
ln -s $DOTFILES/solargraph/solargraph.yml $HOME/.solargraph.yml

# homebrew
# rm -rf $HOME/Brewfile
# ln -s $DOTFILES/homebrew/Brewfile $HOME/Brewfile
# brew install

