# https://alacritty.org/config-alacritty.html

import = [
    "~/.config/alacritty/colorscheme.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 16
offset = { x = 0, y = 8 }

[font.normal]
family = "MesloLGL Nerd Font"

[font.bold]
family = "MesloLGL Nerd Font"

[window]
decorations = "none"
# startup_mode = "fullscreen"
title = "Terminal"
dynamic_title = false
opacity = 1

[window.padding]
x = 0
y = 0
